name: Build

on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Build on ${{matrix.os}}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@master
      - name: Use Node.js 13.x
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 13.x
      - name: Install dependencies
        run: |
          npm install
      - name: Build
        run: |
          npm ci
          npm run build
        env:
          CI: true
